sudo: false

language: go

go:
  - 1.5.1

branches:
  only:
    - master

before_script: |-
  curl -L -o consul.zip https://releases.hashicorp.com/consul/0.6.0-rc2/consul_0.6.0-rc2_linux_amd64.zip
  unzip consul.zip
  mv consul ~/bin/

script: make updatedeps test testrace
